pipeline {
    agent any
    environment {
        MVN_HOME = tool 'maven'
    }

    stages {
        stage('下载代码') {
            steps {
                git branch: '58suo', credentialsId: '37c9366b-5cc4-4312-be20-c81c8f911fab', url: 'https://gitee.com/syouketu/code-generator.git'
            }
        }

        stage('编译代码') {
            steps {
                sh '''
                cd ./back-end
                ${MVN_HOME}/bin/mvn clean install -Dmaven.test.skip=true
                '''
            }
        }

        stage('构建Docker镜像') {
            steps {
                echo '******************************开始构建镜像******************************'
                sh '''
                cd ./back-end
                ${MVN_HOME}/bin/mvn dockerfile:build dockerfile:push
                '''
            }
        }

        stage('部署到集群') {
            steps {
                echo '部署镜像到开发环境'
                rancherRedeploy alwaysPull: true, credential: 'Rancher2', images: '', workload: '/project/c-sxxln:p-hzpzk/workloads/deployment:common:code-generator-api'
            }
        }
    }
}
